version: '3.9'
services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    volumes:
      - .:/srv/jekyll
      - jekyll_cache:/srv/jekyll/_site
    command: jekyll serve --host 0.0.0.0 --watch --force_polling
    ports:
      - "4000:4000"

volumes:
  jekyll_cache:
